error_request = {
    'jsonrpc': '2.0',
    'id': 1,
    'error': {
        'message': 'Error!!',
        'code': 1,
        'data': 'data'
    }
}

accounts = {'jsonrpc': '2.0', 'id': 1, 'result': {'itemId': 0, 'count': 10, 'resultMessage': None, 'result': [
    {'id': 2, 'notes': 'test\r\nmultiple\r\nlines...with <p>tag</p>', 'userLogin': 'admin',
     'dateEdit': '2019-08-22 22:13:41', 'userEditId': 0, 'num_files': 2, 'userId': 1, 'url': 'https://aws.amazon.com/',
     'name': 'Amazon AWS', 'clientName': 'Amazon', 'userGroupId': 1, 'userEditName': '', 'userGroupName': 'Admins',
     'categoryId': 2, 'countView': 92, 'clientId': 5, 'isPrivate': 0, 'userName': 'Administrator',
     'publicLinkHash': '37cd2c5c0a720b88bd4d06a318ca68e336eb241ae4cc41d18c52196f7283', 'categoryName': 'HTTP',
     'passDate': 1548499697, 'isPrivateGroup': 0, 'otherUserGroupEdit': 0, 'publicLinkTotalCountViews': 4,
     'parentId': 0, 'userEditLogin': '', 'otherUserEdit': 0, 'login': 'admin', 'publicLinkDateExpire': 1551038163,
     'passDateChange': None},
    {'id': 11, 'notes': '', 'userLogin': 'admin', 'dateEdit': '2019-02-23 11:56:11', 'userEditId': 0, 'num_files': 0,
     'userId': 1, 'url': 'https://aws.amazon.com/', 'name': 'Amazon AWS (copy)', 'clientName': 'Amazon',
     'userGroupId': 1, 'userEditName': '', 'userGroupName': 'Admins', 'categoryId': 2, 'countView': 9, 'clientId': 5,
     'isPrivate': 0, 'userName': 'Administrator', 'publicLinkHash': None, 'categoryName': 'HTTP',
     'passDate': 1550922971, 'isPrivateGroup': 0, 'otherUserGroupEdit': 0, 'publicLinkTotalCountViews': None,
     'parentId': 0, 'userEditLogin': '', 'otherUserEdit': 0, 'login': 'admin', 'publicLinkDateExpire': None,
     'passDateChange': None},
    {'id': 14, 'notes': 'a', 'userLogin': 'admin', 'dateEdit': '2019-02-24 22:25:50', 'userEditId': 0, 'num_files': 0,
     'userId': 1, 'url': 'https://aws.amazon.com/', 'name': 'Amazon AWS (owner)', 'clientName': 'Amazon',
     'userGroupId': 2, 'userEditName': '', 'userGroupName': 'Users', 'categoryId': 2, 'countView': 26, 'clientId': 5,
     'isPrivate': 0, 'userName': 'Administrator', 'publicLinkHash': None, 'categoryName': 'HTTP',
     'passDate': 1551042477, 'isPrivateGroup': 0, 'otherUserGroupEdit': 0, 'publicLinkTotalCountViews': None,
     'parentId': 0, 'userEditLogin': '', 'otherUserEdit': 0, 'login': 'admin', 'publicLinkDateExpire': None,
     'passDateChange': None},
    {'id': 5, 'notes': '', 'userLogin': 'admin', 'dateEdit': None, 'userEditId': 0, 'num_files': 0, 'userId': 1,
     'url': 'https://www.ing.com', 'name': 'ING direct', 'clientName': 'Financial Department', 'userGroupId': 1,
     'userEditName': '', 'userGroupName': 'Admins', 'categoryId': 24, 'countView': 0, 'clientId': 6, 'isPrivate': None,
     'userName': 'Administrator', 'publicLinkHash': None, 'categoryName': 'Banking', 'passDate': 1545667228,
     'isPrivateGroup': None, 'otherUserGroupEdit': 0, 'publicLinkTotalCountViews': None, 'parentId': None,
     'userEditLogin': '', 'otherUserEdit': 0, 'login': 'ing456963147', 'publicLinkDateExpire': None,
     'passDateChange': None},
    {'id': 1, 'notes': '', 'userLogin': 'admin', 'dateEdit': '2018-12-24 16:03:39', 'userEditId': 0, 'num_files': 0,
     'userId': 1,
     'url': 'https://accounts.google.com/signin/v2/identifier?passive=true&continue=https%3A%2F%2Fcloud.google.com%2F%3Frefresh%3D1&service=cloudconsole&flowName=GlifWebSignIn&flowEntry=ServiceLogin',
     'name': 'Google Cloud', 'clientName': 'Google', 'userGroupId': 1, 'userEditName': '', 'userGroupName': 'Admins',
     'categoryId': 2, 'countView': 2, 'clientId': 1, 'isPrivate': 0, 'userName': 'Administrator',
     'publicLinkHash': None, 'categoryName': 'HTTP', 'passDate': 1545667228, 'isPrivateGroup': 0,
     'otherUserGroupEdit': 0, 'publicLinkTotalCountViews': None, 'parentId': 0, 'userEditLogin': '', 'otherUserEdit': 0,
     'login': 'admin', 'publicLinkDateExpire': None, 'passDateChange': None},
    {'id': 7, 'notes': 'testaaaaa', 'userLogin': 'admin', 'dateEdit': '2019-04-26 19:19:06', 'userEditId': 0,
     'num_files': 0, 'userId': 1, 'url': 'https://contoso.com', 'name': 'Contoso VPN', 'clientName': 'IT Department',
     'userGroupId': 1, 'userEditName': '', 'userGroupName': 'Admins', 'categoryId': 25, 'countView': 9, 'clientId': 7,
     'isPrivate': 0, 'userName': 'Administrator', 'publicLinkHash': None, 'categoryName': 'Certificates',
     'passDate': 1545667228, 'isPrivateGroup': 0, 'otherUserGroupEdit': 0, 'publicLinkTotalCountViews': None,
     'parentId': 0, 'userEditLogin': '', 'otherUserEdit': 0, 'login': 'homer@contoso.com', 'publicLinkDateExpire': None,
     'passDateChange': None},
    {'id': 6, 'notes': '', 'userLogin': 'admin', 'dateEdit': '2019-02-07 18:56:17', 'userEditId': 0, 'num_files': 0,
     'userId': 1, 'url': 'ssh://dropboc.com', 'name': 'Dropbox', 'clientName': 'IT Department', 'userGroupId': 1,
     'userEditName': '', 'userGroupName': 'Admins', 'categoryId': 2, 'countView': 7, 'clientId': 7, 'isPrivate': 0,
     'userName': 'Administrator', 'publicLinkHash': None, 'categoryName': 'HTTP', 'passDate': 1545667228,
     'isPrivateGroup': 1, 'otherUserGroupEdit': 0, 'publicLinkTotalCountViews': None, 'parentId': 0,
     'userEditLogin': '', 'otherUserEdit': 0, 'login': 'bigbang@dropbox.com', 'publicLinkDateExpire': None,
     'passDateChange': None},
    {'id': 4, 'notes': 'r0lJXvN97<test<div></div>', 'userLogin': 'admin', 'dateEdit': '2019-04-26 18:59:51',
     'userEditId': 0, 'num_files': 0, 'userId': 1, 'url': '10.0.0.20', 'name': 'Exchange Server',
     'clientName': 'IT Department', 'userGroupId': 1, 'userEditName': '', 'userGroupName': 'Admins', 'categoryId': 27,
     'countView': 24, 'clientId': 7, 'isPrivate': 0, 'userName': 'Administrator', 'publicLinkHash': None,
     'categoryName': 'RDP', 'passDate': 1545667228, 'isPrivateGroup': 0, 'otherUserGroupEdit': 0,
     'publicLinkTotalCountViews': None, 'parentId': 0, 'userEditLogin': '', 'otherUserEdit': 0, 'login': 'administ',
     'publicLinkDateExpire': None, 'passDateChange': None},
    {'id': 3, 'notes': '', 'userLogin': 'admin', 'dateEdit': '2018-12-24 16:06:20', 'userEditId': 0, 'num_files': 0,
     'userId': 1, 'url': '10.0.0.10', 'name': 'wiki:DC Server', 'clientName': 'IT Department', 'userGroupId': 1,
     'userEditName': '', 'userGroupName': 'Admins', 'categoryId': 27, 'countView': 3, 'clientId': 7, 'isPrivate': 0,
     'userName': 'Administrator', 'publicLinkHash': None, 'categoryName': 'RDP', 'passDate': 1545667228,
     'isPrivateGroup': 0, 'otherUserGroupEdit': 0, 'publicLinkTotalCountViews': None, 'parentId': 0,
     'userEditLogin': '', 'otherUserEdit': 0, 'login': 'administrator@contoso.com', 'publicLinkDateExpire': None,
     'passDateChange': None},
    {'id': 8, 'notes': '', 'userLogin': 'admin', 'dateEdit': None, 'userEditId': 0, 'num_files': 0, 'userId': 1,
     'url': '10.0.0.11', 'name': 'wiki:vm-monitor', 'clientName': 'IT Department', 'userGroupId': 1, 'userEditName': '',
     'userGroupName': 'Admins', 'categoryId': 28, 'countView': 1, 'clientId': 7, 'isPrivate': None,
     'userName': 'Administrator', 'publicLinkHash': None, 'categoryName': 'SSH', 'passDate': 1545667228,
     'isPrivateGroup': None, 'otherUserGroupEdit': 0, 'publicLinkTotalCountViews': None, 'parentId': None,
     'userEditLogin': '', 'otherUserEdit': 0, 'login': 'root', 'publicLinkDateExpire': None, 'passDateChange': None}],
                                                  'resultCode': 0}}

categories = {'jsonrpc': '2.0', 'id': 2, 'result': {'itemId': 0, 'count': 7, 'resultMessage': None, 'result': [
    {'id': 24, 'name': 'Banking', 'description': 'Banking services'},
    {'id': 25, 'name': 'Certificates', 'description': 'PKI certificates'},
    {'id': 26, 'name': 'Databases', 'description': ''}, {'id': 2, 'name': 'HTTP', 'description': ''},
    {'id': 27, 'name': 'RDP', 'description': 'RDP based services'},
    {'id': 28, 'name': 'SSH', 'description': 'SSH based services'}, {'id': 1, 'name': 'Web', 'description': ''}],
                                                    'resultCode': 0}}

clients = {'jsonrpc': '2.0', 'id': 3, 'result': {'itemId': 0, 'count': 6, 'resultMessage': None, 'result': [
    {'id': 5, 'name': 'Amazon', 'hash': '', 'isGlobal': 0, 'description': ''},
    {'id': 6, 'name': 'Financial Department', 'hash': '', 'isGlobal': 0, 'description': ''},
    {'id': 1, 'name': 'Google', 'hash': '', 'isGlobal': 0, 'description': ''},
    {'id': 2, 'name': 'Google Inc.', 'hash': '', 'isGlobal': 0, 'description': ''},
    {'id': 7, 'name': 'IT Department', 'hash': '', 'isGlobal': 0, 'description': ''},
    {'id': 3, 'name': 'Microsoft Inc', 'hash': '', 'isGlobal': 0, 'description': ''}], 'resultCode': 0}}

tags = {'jsonrpc': '2.0', 'id': 4, 'result': {'itemId': 0, 'count': 12, 'resultMessage': None,
                                              'result': [{'id': 2, 'name': 'AWS'}, {'id': 3, 'name': 'Azure'},
                                                         {'id': 12, 'name': 'Cloud'}, {'id': 4, 'name': 'GCP'},
                                                         {'id': 5, 'name': 'JBoss'}, {'id': 6, 'name': 'Mail server'},
                                                         {'id': 7, 'name': 'MariaDB'}, {'id': 8, 'name': 'Oracle'},
                                                         {'id': 9, 'name': 'PostgreSQL'}, {'id': 10, 'name': 'Tomcat'},
                                                         {'id': 11, 'name': 'Webserver'}, {'id': 1, 'name': 'WWW'}],
                                              'resultCode': 0}}

user_groups = {'jsonrpc': '2.0', 'id': 5, 'result': {'itemId': 0, 'count': 2, 'resultMessage': None, 'result': [
    {'id': 1, 'name': 'Admins', 'users': None, 'description': 'sysPass Admins'},
    {'id': 2, 'name': 'Users', 'users': None, 'description': ''}], 'resultCode': 0}}
