__title__ = 'syspass-api-client'
__description__ = 'sysPass API client library for Python.'
__url__ = 'https://github.com/sysPass/syspass-api-client-python'
__version__ = '0.1.3'
__build__ = 19090601
__author__ = 'Rubén Domínguez'
__author_email__ = 'nuxsmin@syspass.org'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2019 Rubén Domínguez'
